# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
