# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170810_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='video_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
