# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(help_text='Input language(e.g. english, russian, ukranian)', related_name='native_language', through='main.UserLanguage', to='main.Language'),
        ),
    ]
