# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(help_text='Input language(e.g. english, russian, ukranian)', through='main.UserLanguage', to='main.Language'),
        ),
    ]
