# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170714_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguage',
            name='native',
        ),
    ]
