# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_userlanguage_native'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(help_text='Input language(e.g. english, russian, ukranian)', to='main.Language'),
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
    ]
