version: '3'
services:
  nginx:
    restart: always
    build: ./nginx/
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./web:/src
    links:
      - web


  web:
    restart: always
    build: ./web
    container_name: spnt01
    expose:
      - "8000"
    depends_on:
      - postgres
    volumes:
      - ./web:/src/
    links:
      - postgres
    env_file: .env
    command: bash -c " python manage.py collectstatic --noinput &&
                       python manage.py makemigrations &&
                       python manage.py migrate &&
                       gunicorn project.wsgi:application -w 2 -b :8000"

  postgres:
    restart: always
    image: postgres:latest
    container_name: db01
    env_file: .env
    ports:
      - "5432:5432"
    #volumes:
     #- ./pgdata:/var/lib/postgresql/data/
