# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170823_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='dt_from',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='dt_to',
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day_of_week',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=2),
        ),
    ]
