# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20170829_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')]),
        ),
    ]
