# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170312_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], help_text='Choose your level', max_length=2),
        ),
    ]
